
import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "جهاز عرض المجرات الذكي (Galaxy Projector)",
    price: 89,
    originalPrice: 150,
    category: "إلكترونيات منزلية",
    image: "https://images.unsplash.com/photo-1534234828563-02511456e58d?q=80&w=800&auto=format&fit=crop",
    shortDescription: "حول غرفتك إلى فضاء خارجي ساحر مع إضاءة ليزر ذكية.",
    rating: 4.9,
    reviewsCount: 1240,
    supplier: 'DSers Verified',
    shippingTime: "7-12 يوم",
    shippingPrice: 0,
    isHot: true
  },
  {
    id: 2,
    name: "أداة إزالة الشعر الكريستالية",
    price: 45,
    originalPrice: 99,
    category: "عناية شخصية",
    image: "https://images.unsplash.com/photo-1621239950518-314b831b1324?q=80&w=800&auto=format&fit=crop",
    shortDescription: "بدون ألم، قابلة لإعادة الاستخدام، وناعمة على البشرة.",
    rating: 4.7,
    reviewsCount: 850,
    supplier: 'AliExpress',
    shippingTime: "10-15 يوم",
    shippingPrice: 15,
    isHot: true
  },
  {
    id: 3,
    name: "مصحح وضعية الظهر الذكي",
    price: 65,
    originalPrice: 120,
    category: "صحة وجمال",
    image: "https://images.unsplash.com/photo-1544367563-12123d8965cd?q=80&w=800&auto=format&fit=crop",
    shortDescription: "تنبيه اهتزازي لتصحيح الجلوس وتخفيف آلام الظهر.",
    rating: 4.5,
    reviewsCount: 320,
    supplier: 'AliExpress',
    shippingTime: "12-18 يوم",
    shippingPrice: 10
  },
  {
    id: 4,
    name: "خلاط محمول قابل للشحن",
    price: 79,
    originalPrice: 140,
    category: "مطبخ",
    image: "https://images.unsplash.com/photo-1595535943317-8914274b690f?q=80&w=800&auto=format&fit=crop",
    shortDescription: "عصير طازج في أي مكان. قوي وسهل التنظيف.",
    rating: 4.8,
    reviewsCount: 2100,
    supplier: 'DSers Verified',
    shippingTime: "5-9 أيام",
    shippingPrice: 0,
    isHot: true
  },
  {
    id: 5,
    name: "سماعات الرأس اللاسلكية P9",
    price: 55,
    originalPrice: 199,
    category: "إلكترونيات",
    image: "https://images.unsplash.com/photo-1613040809024-b4ef7ba99bc3?q=80&w=800&auto=format&fit=crop",
    shortDescription: "تصميم عصري مشابه للماركات العالمية وعزل ضوضاء.",
    rating: 4.3,
    reviewsCount: 540,
    supplier: 'AliExpress',
    shippingTime: "15-20 يوم",
    shippingPrice: 20
  },
  {
    id: 6,
    name: "مصباح الزاوية LED الذكي",
    price: 120,
    originalPrice: 250,
    category: "ديكور منزلي",
    image: "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?q=80&w=800&auto=format&fit=crop",
    shortDescription: "إضاءة RGB قابلة للتحكم عبر التطبيق لإضافة جو سينمائي.",
    rating: 4.6,
    reviewsCount: 110,
    supplier: 'DSers Verified',
    shippingTime: "8-14 يوم",
    shippingPrice: 0
  },
  {
    id: 7,
    name: "منظف الأحذية الكهربائي",
    price: 35,
    originalPrice: 70,
    category: "أدوات منزلية",
    image: "https://images.unsplash.com/photo-1604671801908-6f0c6a092c05?q=80&w=800&auto=format&fit=crop",
    shortDescription: "تنظيف عميق وتلميع للأحذية الرياضية والجلدية.",
    rating: 4.4,
    reviewsCount: 95,
    supplier: 'AliExpress',
    shippingTime: "10-20 يوم",
    shippingPrice: 18
  },
  {
    id: 8,
    name: "حقيبة ظهر مضادة للسرقة",
    price: 95,
    originalPrice: 180,
    category: "سفر",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=800&auto=format&fit=crop",
    shortDescription: "تصميم خفي للسحابات مع منفذ USB للشحن.",
    rating: 4.9,
    reviewsCount: 3400,
    supplier: 'Local Warehouse',
    shippingTime: "2-4 أيام",
    shippingPrice: 0,
    isHot: true
  }
];
